export const STUDIO = {
  en: {
    'hero.studioRole': 'Independent developer · Creative technologist',
    'hero.headline': 'One mind.\nMany possibilities.',
    'hero.intro': 'I’m Kourosh. I connect design, code and technology to turn your ideas into working digital products. From the first sketch to the final release.',
    'hero.work': 'Explore my work ↗', 'hero.resume': 'My experience ↓',
    'hero.code': 'Code', 'hero.model': 'Form', 'hero.system': 'System',
    'hero.interact': 'Move your pointer to explore',
    'about.studioTitle': 'The person behind the possibilities.',
    'about.studioBody': 'A developer with a builder’s mindset. I work across interfaces, backend systems and databases, bringing the pieces together into one useful product. You work directly with the person who understands, designs and builds your solution.',
    'about.signature': 'Kourosh Moradi / Independent digital practice',
    'services.studioTitle': 'From an idea to something real.',
    'services.studioIntro': 'A connected set of capabilities for building, launching and maintaining your digital product.',
    'projects.studioTitle': 'Built to solve real problems.',
    'projects.studioIntro': 'Three different industries. The same attention to how people actually work.',
    'contact.studioTitle': 'Let’s build your next possibility.',
    'contact.studioIntro': 'Have a business challenge, a product idea or a role in mind? Tell me what you want to make happen.',
    'exp.print': 'Print / save résumé ↗',
  },
  fa: {
    'hero.studioRole': 'توسعه‌دهندهٔ مستقل · سازندهٔ تجربه‌های دیجیتال',
    'hero.headline': 'یک ذهن.\nهزار امکان.',
    'hero.intro': 'من کوروشم. طراحی، کد و تکنولوژی را به هم وصل می‌کنم تا ایده‌هایت به محصولی کاربردی تبدیل شوند. از اولین طرح تا آخرین مرحلهٔ اجرا.',
    'hero.work': 'کشف نمونه‌کارها ↗', 'hero.resume': 'مسیر حرفه‌ای من ↓',
    'hero.code': 'کد', 'hero.model': 'مدل', 'hero.system': 'سیستم',
    'hero.interact': 'با حرکت نشانگر، مدل را کشف کن',
    'about.studioTitle': 'آدمِ پشت این همه امکان.',
    'about.studioBody': 'توسعه‌دهنده‌ای با ذهنیت ساختن. از رابط کاربری تا منطق سرور و پایگاه داده، بخش‌های مختلف را به یک محصول کاربردی وصل می‌کنم. مستقیم با کسی کار می‌کنی که مسئله‌ات را می‌فهمد، راه‌حلش را طراحی می‌کند و آن را می‌سازد.',
    'about.signature': 'کوروش مرادی / طراحی و توسعهٔ مستقل',
    'services.studioTitle': 'از یک ایده تا یک محصول واقعی.',
    'services.studioIntro': 'مجموعه‌ای از مهارت‌های مکمل برای ساخت، راه‌اندازی و نگهداری محصول دیجیتال تو.',
    'projects.studioTitle': 'ساخته‌شده برای مسئله‌های واقعی.',
    'projects.studioIntro': 'سه حوزهٔ متفاوت، با یک نگاه مشترک: ساده‌تر کردن کار آدم‌ها.',
    'contact.studioTitle': 'امکان بعدی را با هم بسازیم.',
    'contact.studioIntro': 'یک چالش کاری، ایدهٔ محصول یا فرصت همکاری داری؟ برایم بنویس چه چیزی می‌خواهی بسازی.',
    'exp.print': 'چاپ / ذخیرهٔ رزومه ↗',
  },
};
